# Generated by Django 4.1.5 on 2023-01-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event2all', '0002_todolist_quotation_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
