# Generated by Django 4.1.5 on 2023-01-30 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event2all', '0005_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='contact',
            new_name='content',
        ),
    ]
